spring:
  application:
    name: eureka
server:
  port: 1001
eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    ip-address: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    status-page-url: http://${spring.cloud.client.ip-address}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-b:1002/eureka,http://eureka-a:1001/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000