spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GLepoch/springcloud-group-demo.git
          search-paths: configserver/comm-config,configserver/single-config/{application}
          username: GLepoch
          password: l537073101
server:
  port: 5001